from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import re
import sys
from pathlib import Path
from typing import Iterable


REQUIRED_FILES = [
    "AGENTS.md",
    "package.json",
    "tools/__init__.py",
    "tools/governance.py",
    "tests/test_governance.py",
    "docs/AI_STANDARD.md",
    "docs/WORKFLOW.md",
    "docs/CONTROLS.md",
    "docs/UI_STANDARD.md",
    "project/00_input/需求输入.md",
    "project/01_specification/产品需求说明书.md",
    "project/02_solution/架构设计说明书.md",
    "project/03_modules/模块任务开发说明书.md",
    "project/04_tests/测试说明书.md",
    "project/05_evidence/README.md",
    "project/06_changes/README.md",
    "project/07_releases/版本发布控制说明书.md",
]

PROJECT_DIRS = [
    "tools",
    "tests",
    "project/00_input",
    "project/01_specification",
    "project/02_solution",
    "project/03_modules",
    "project/04_tests",
    "project/05_evidence",
    "project/06_changes",
    "project/07_releases",
]

CONTROL_DIR = Path("project/.governance")
BASELINE_PATH = CONTROL_DIR / "baseline.json"
LEDGER_PATH = CONTROL_DIR / "ledger.jsonl"
TEST_RESULTS_PATH = Path("project/05_evidence/test-results.json")
UI_STANDARD_PATH = Path("docs/UI_STANDARD.md")

UI_REQUIRED_MARKERS = [
    "UI-GOV-001",
    "Design Tokens",
    "WCAG 2.2 AA",
    "WAI-ARIA Authoring Practices",
    "Component-Driven Development",
    "Testing Library",
    "Playwright",
    "real-entry",
    "third-party provider authorization",
]

UI_REQUIRED_SCRIPTS = [
    "test:auth-ui",
    "test:visual",
    "test:e2e",
    "test:ui-contract",
    "governance:ui",
]

UI_CONTRACT_SCRIPT_PATH = Path("scripts/ui-contract.mjs")

IGNORED_DIR_NAMES = {
    ".git",
    ".data",
    ".next",
    ".turbo",
    ".vercel",
    ".vscode",
    "__pycache__",
    "coverage",
    "node_modules",
    "playwright-report",
    "test-results",
}

# Framework-managed build directories (next.config.mjs NEXT_DIST_DIR isolation).
IGNORED_DIR_PREFIXES = (".next-",)

IGNORED_FILE_NAMES = {
    ".env",
    ".env.local",
    ".env.development",
    ".env.test",
    ".env.production",
    # Regenerated by Next.js on every build/dev; content is not author-controlled.
    "next-env.d.ts",
}

IGNORED_SUFFIXES = {
    ".db",
    ".db-shm",
    ".db-wal",
    ".log",
    ".pyc",
    ".sqlite",
    ".sqlite3",
    ".tsbuildinfo",
}

PLACEHOLDER_MARKERS = [
    "未批准",
    "尚未确认",
    "尚未与用户确认",
    "等待用户确认",
    "产品需求尚未",
    "产品功能需求尚未",
]

CHANGE_REQUIRED_LABELS = [
    "级别",
    "提出人",
    "状态",
    "影响需求",
    "影响模块",
    "影响任务",
    "影响测试",
    "当前证据",
    "方案选项",
    "选择理由",
    "回滚方式",
    "验收条件",
    "评审记录",
]


def run(argv: list[str] | None = None) -> tuple[int, str]:
    parser = build_parser()
    args = parser.parse_args(argv)
    root = Path(args.root).resolve()

    if args.command == "verify":
        messages = verify(root)
    elif args.command == "gate":
        messages = gate(root, args.gate.lower(), cr=args.cr)
    elif args.command == "snapshot":
        messages = snapshot(root, args.actor)
    elif args.command == "check-changes":
        messages = check_changes(root)
    elif args.command == "ui":
        messages = check_ui_process_control(root)
    elif args.command == "review":
        messages = check_review(root, args.level.lower(), cr=args.cr)
    elif args.command == "check":
        messages = check_stage(root, args.stage, cr=args.cr)
    elif args.command == "check-specs":
        messages = check_specs(root)
    elif args.command == "new-cr":
        messages = new_cr(root, args.name)
    elif args.command == "matrix":
        messages = build_matrices(root, args.cr_name, force=args.force)
    else:
        parser.error("unknown command")

    code = 0 if all(message.startswith("OK ") for message in messages) else 1
    return code, "\n".join(messages) + "\n"


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Agent-Jarvis governance control CLI")
    subparsers = parser.add_subparsers(dest="command", required=True)

    verify_parser = subparsers.add_parser("verify", help="verify required governance files and baseline integrity")
    verify_parser.add_argument("--root", default=".", help="project root")

    gate_parser = subparsers.add_parser("gate", help="run a governance gate")
    gate_parser.add_argument("gate", choices=["g1", "g2", "g3", "g3.5", "g4"])
    gate_parser.add_argument("--root", default=".", help="project root")
    gate_parser.add_argument("--cr", default=None, help="narrow the judgement to one change record (not for g4)")

    snapshot_parser = subparsers.add_parser("snapshot", help="write baseline hashes and append a ledger event")
    snapshot_parser.add_argument("--root", default=".", help="project root")
    snapshot_parser.add_argument("--actor", default="unknown", help="actor recorded in the ledger")

    changes_parser = subparsers.add_parser("check-changes", help="validate change records")
    changes_parser.add_argument("--root", default=".", help="project root")

    ui_parser = subparsers.add_parser("ui", help="validate UI process controls")
    ui_parser.add_argument("--root", default=".", help="project root")

    review_parser = subparsers.add_parser(
        "review", help="validate a consensus review gate (CR-20260909-consensus-review-gates model)"
    )
    review_parser.add_argument("level", choices=["r1", "r2", "r3", "r4"])
    review_parser.add_argument("--root", default=".", help="project root")
    review_parser.add_argument("--cr", default=None, help="narrow the judgement to one change record")

    check_parser = subparsers.add_parser("check", help="run every gate a stage requires (p1|p2|p3|release)")
    check_parser.add_argument("stage", choices=["p1", "p2", "p3", "release"])
    check_parser.add_argument("--root", default=".", help="project root")
    check_parser.add_argument("--cr", default=None, help="narrow the judgement to one change record (not for release)")

    specs_parser = subparsers.add_parser("check-specs", help="validate the spec structure contract (DEC-020)")
    specs_parser.add_argument("--root", default=".", help="project root")

    new_cr_parser = subparsers.add_parser("new-cr", help="scaffold a compliant change record")
    new_cr_parser.add_argument("name", help="change record name, e.g. CR-20260911-my-change")
    new_cr_parser.add_argument("--root", default=".", help="project root")

    matrix_parser = subparsers.add_parser("matrix", help="generate R2/R3/R4 review matrix skeletons from the CP registry")
    matrix_parser.add_argument("cr_name", metavar="cr", help="change record name")
    matrix_parser.add_argument("--root", default=".", help="project root")
    matrix_parser.add_argument("--force", action="store_true", help="rewrite matrices that already exist")

    return parser


def verify(root: Path) -> list[str]:
    findings: list[str] = []
    findings.extend(check_required_structure(root))
    findings.extend(m for m in check_ui_process_control(root) if not m.startswith("OK "))
    findings.extend(check_baseline(root))
    findings.extend(check_ledger(root))

    if findings:
        return findings
    return ["OK VERIFY_PASS governance files and integrity checks passed"]


def gate(root: Path, gate_name: str, cr: str | None = None) -> list[str]:
    structure_findings = check_required_structure(root)
    if structure_findings:
        return structure_findings

    if gate_name == "g1":
        return check_g1(root)
    if gate_name == "g2":
        g1 = check_g1(root)
        if not is_ok(g1):
            return ["FAIL G2_BLOCKED G1 must pass before G2"] + g1
        return check_g2(root)
    if gate_name == "g3":
        g2 = gate(root, "g2")
        if not is_ok(g2):
            return ["FAIL G3_BLOCKED G2 must pass before implementation validation"] + g2
        return check_g3(root, cr=cr)
    if gate_name == "g3.5":
        g3 = gate(root, "g3", cr=cr)
        if not is_ok(g3):
            return ["FAIL G3_5_BLOCKED G3 must pass before real-entry smoke validation"] + g3
        return check_g35(root, cr=cr)
    if gate_name == "g4":
        # A release is judged at full scope by definition: a narrowing view must
        # never be able to relax it (CR-20260910-process-hardening CP-5).
        if cr:
            return ["FAIL G4_BLOCKED release must be judged at full scope; --cr is not accepted"]
        lower = gate(root, "g3.5")
        if not is_ok(lower):
            return ["FAIL G4_BLOCKED G3.5 must pass before release"] + lower
        return check_g4(root)
    return [f"FAIL UNKNOWN_GATE unsupported gate: {gate_name}"]


def snapshot(root: Path, actor: str) -> list[str]:
    findings = check_required_structure(root)
    if findings:
        return findings

    baseline = {
        "schema_version": 1,
        "created_at": now_utc(),
        "files": {rel_path: governed_hash(root / rel_path, rel_path) for rel_path in discover_controlled_files(root)},
    }
    baseline_json = canonical_json(baseline)
    baseline["baseline_sha256"] = sha256_text(baseline_json)

    baseline_path = root / BASELINE_PATH
    baseline_path.parent.mkdir(parents=True, exist_ok=True)
    baseline_path.write_text(canonical_json(baseline) + "\n", encoding="utf-8")

    ledger_findings = append_ledger_event(
        root,
        {
            "action": "snapshot",
            "actor": actor,
            "payload_sha256": baseline["baseline_sha256"],
            "files": baseline["files"],
        },
    )
    if ledger_findings:
        return ledger_findings

    return [f"OK SNAPSHOT_WRITTEN {to_posix(BASELINE_PATH)}"]


def check_required_structure(root: Path) -> list[str]:
    findings: list[str] = []
    for rel_dir in PROJECT_DIRS:
        if not (root / rel_dir).is_dir():
            findings.append(f"FAIL MISSING_REQUIRED_DIR {rel_dir}")
    for rel_path in REQUIRED_FILES:
        if not (root / rel_path).is_file():
            findings.append(f"FAIL MISSING_REQUIRED_FILE {rel_path}")
    return findings


def check_baseline(root: Path) -> list[str]:
    baseline_path = root / BASELINE_PATH
    if not baseline_path.exists():
        return []

    try:
        baseline = json.loads(baseline_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        return [f"FAIL BASELINE_INVALID_JSON {to_posix(BASELINE_PATH)} {exc}"]

    findings: list[str] = []
    files = baseline.get("files")
    if not isinstance(files, dict):
        return [f"FAIL BASELINE_INVALID_SCHEMA {to_posix(BASELINE_PATH)} missing files object"]

    for rel_path, expected_hash in files.items():
        path = root / rel_path
        if not path.exists():
            findings.append(f"FAIL BASELINE_FILE_MISSING {rel_path}")
            continue
        actual_hash = governed_hash(path, rel_path)
        if actual_hash != expected_hash:
            findings.append(f"FAIL BASELINE_CHANGED {rel_path}")

    current_files = set(discover_controlled_files(root))
    baseline_files = set(files)
    for rel_path in sorted(current_files - baseline_files):
        findings.append(f"FAIL UNBASELINED_FILE {rel_path}")
    return findings


def discover_controlled_files(root: Path) -> list[str]:
    files: list[str] = []
    for path in root.rglob("*"):
        if not path.is_file():
            continue
        rel_path = path.relative_to(root)
        rel_parts = rel_path.parts
        if any(part in IGNORED_DIR_NAMES for part in rel_parts[:-1]):
            continue
        if any(part.startswith(IGNORED_DIR_PREFIXES) for part in rel_parts[:-1]):
            continue
        if rel_path.parts[:2] == ("project", ".governance"):
            continue
        if path.name in IGNORED_FILE_NAMES:
            continue
        if any(path.name.endswith(suffix) for suffix in IGNORED_SUFFIXES):
            continue
        files.append(to_posix(rel_path))
    return sorted(files)


def check_ledger(root: Path) -> list[str]:
    ledger_path = root / LEDGER_PATH
    if not ledger_path.exists():
        return []

    findings: list[str] = []
    previous_hash = "GENESIS"
    expected_seq = 1
    for line_number, line in enumerate(ledger_path.read_text(encoding="utf-8").splitlines(), start=1):
        if not line.strip():
            continue
        try:
            event = json.loads(line)
        except json.JSONDecodeError as exc:
            findings.append(f"FAIL LEDGER_INVALID_JSON line={line_number} {exc}")
            continue

        if event.get("seq") != expected_seq:
            findings.append(f"FAIL LEDGER_BAD_SEQUENCE line={line_number}")
        if event.get("prev_hash") != previous_hash:
            findings.append(f"FAIL LEDGER_BROKEN_CHAIN line={line_number}")

        recorded_hash = event.get("hash")
        event_without_hash = dict(event)
        event_without_hash.pop("hash", None)
        actual_hash = sha256_text(canonical_json(event_without_hash))
        if recorded_hash != actual_hash:
            findings.append(f"FAIL LEDGER_HASH_MISMATCH line={line_number}")

        previous_hash = str(recorded_hash)
        expected_seq += 1

    return findings


def check_g1(root: Path) -> list[str]:
    input_text = read_text(root / "project/00_input/需求输入.md")
    spec_text = read_text(root / "project/01_specification/产品需求说明书.md")
    findings: list[str] = []

    if not meaningful_input_exists(input_text):
        findings.append("FAIL G1_BLOCKED 原始需求输入缺失或尚未建立")
    if contains_placeholder_state(spec_text):
        findings.append("FAIL G1_BLOCKED 产品需求仍处于未确认状态，需要用户确认")
    if not approved_status_exists(spec_text):
        findings.append("FAIL G1_BLOCKED 产品需求说明书缺少 APPROVED 状态")
    if "用户确认" not in spec_text:
        findings.append("FAIL G1_BLOCKED 产品需求说明书缺少用户确认记录")
    if not approved_requirement_row_exists(spec_text):
        findings.append("FAIL G1_BLOCKED 产品需求说明书缺少带验收标准的已批准需求行")

    if findings:
        return findings
    return ["OK G1_PASS requirements baseline is approved and testable"]


def check_g2(root: Path) -> list[str]:
    architecture = read_text(root / "project/02_solution/架构设计说明书.md")
    modules = read_text(root / "project/03_modules/模块任务开发说明书.md")
    tests = read_text(root / "project/04_tests/测试说明书.md")
    findings: list[str] = []

    for rel_path, text in [
        ("project/02_solution/架构设计说明书.md", architecture),
        ("project/03_modules/模块任务开发说明书.md", modules),
        ("project/04_tests/测试说明书.md", tests),
    ]:
        if contains_placeholder_state(text):
            findings.append(f"FAIL G2_BLOCKED {rel_path} is still unapproved")

    requirement_ids = extract_ids(read_text(root / "project/01_specification/产品需求说明书.md"), "REQ")
    module_requirement_ids = extract_ids(modules, "REQ")
    test_requirement_ids = extract_ids(tests, "REQ")
    task_ids = extract_ids(modules, "TASK")
    test_ids = extract_ids(tests, "TEST")

    missing_module_coverage = sorted(requirement_ids - module_requirement_ids)
    missing_test_coverage = sorted(requirement_ids - test_requirement_ids)
    if missing_module_coverage:
        findings.append(f"FAIL G2_BLOCKED requirements missing module coverage: {', '.join(missing_module_coverage)}")
    if missing_test_coverage:
        findings.append(f"FAIL G2_BLOCKED requirements missing test coverage: {', '.join(missing_test_coverage)}")
    if not task_ids:
        findings.append("FAIL G2_BLOCKED no TASK ids defined")
    if not test_ids:
        findings.append("FAIL G2_BLOCKED no TEST ids defined")

    if findings:
        return findings
    return ["OK G2_PASS architecture, modules, and tests cover approved requirements"]


def check_g4(root: Path) -> list[str]:
    release_text = read_text(root / "project/07_releases/版本发布控制说明书.md")
    findings: list[str] = []
    if contains_placeholder_state(release_text):
        findings.append("FAIL G4_BLOCKED release control is still unapproved")
    if "回滚" not in release_text:
        findings.append("FAIL G4_BLOCKED release control missing rollback instructions")
    if findings:
        return findings
    return ["OK G4_PASS release control is approved"]


def check_g3(root: Path, cr: str | None = None) -> list[str]:
    required_tests = extract_ids(read_text(root / "project/04_tests/测试说明书.md"), "TEST")
    if cr:
        # CP-5: a narrowing view for an in-flight CR. The default (cr=None) keeps the
        # full-scope semantics untouched — another CR's unfinished work must still
        # block a release, it just should not block this CR's own self-check.
        scoped = cr_related_tests(root, cr)
        if scoped is None:
            return [f"FAIL G3_BLOCKED unknown change record: {cr}"]
        required_tests = required_tests & scoped
    evidence = load_test_results(root)
    if isinstance(evidence, str):
        return [evidence]

    results = {item.get("id"): item for item in evidence}
    missing = sorted(test_id for test_id in required_tests if test_id not in results)

    def is_manual(item: dict[str, object]) -> bool:
        return str(item.get("verification", "")).lower() == "manual"

    def is_deferred(item: dict[str, object]) -> bool:
        # A test bound only to a requirement that has been formally deferred
        # (its "blocks" requirement is DEFERRED in the spec). It is not evidence
        # of a shipped behaviour, so it neither passes nor blocks — it is skipped
        # and reported, and returns with the deferring CR.
        return str(item.get("result", "")).upper() == "DEFERRED"

    pending_manual: list[str] = []
    unattributed_manual: list[str] = []
    deferred: list[str] = []
    failed: list[str] = []

    for test_id in sorted(required_tests):
        item = results.get(test_id)
        if item is None:
            continue
        passed = str(item.get("result", "")).upper() == "PASS"
        if is_deferred(item):
            deferred.append(test_id)
        elif is_manual(item):
            # A manual item cannot be satisfied by a bare "PASS": it must name
            # who verified it and when, so it stays auditable and cannot be
            # silently flipped to green.
            if not passed:
                pending_manual.append(test_id)
            elif not (str(item.get("verified_by", "")).strip() and str(item.get("verified_at", "")).strip()):
                unattributed_manual.append(test_id)
        elif not passed:
            failed.append(test_id)

    findings: list[str] = []
    if missing:
        findings.append(f"FAIL G3_BLOCKED missing PASS evidence for: {', '.join(missing)}")
    if failed:
        findings.append(f"FAIL G3_BLOCKED failing test evidence for: {', '.join(failed)}")
    if pending_manual:
        findings.append(
            "FAIL G3_BLOCKED manual verification pending (a human must run it and record "
            f"verified_by/verified_at): {', '.join(pending_manual)}"
        )
    if unattributed_manual:
        findings.append(
            "FAIL G3_BLOCKED manual verification marked PASS without verified_by/verified_at: "
            f"{', '.join(unattributed_manual)}"
        )
    if findings:
        return findings
    if deferred:
        return [
            "OK G3_PASS all non-deferred required tests have current PASS evidence "
            f"(deferred, tracked by their CR: {', '.join(deferred)})"
        ]
    return ["OK G3_PASS all required tests have current PASS evidence"]


def check_g35(root: Path, cr: str | None = None) -> list[str]:
    evidence = load_test_results(root)
    if isinstance(evidence, str):
        return [evidence.replace("G3_BLOCKED", "G3_5_BLOCKED")]

    if cr:
        scoped = cr_related_tests(root, cr)
        if scoped is None:
            return [f"FAIL G3_5_BLOCKED unknown change record: {cr}"]
        evidence = [item for item in evidence if item.get("id") in scoped]

    for item in evidence:
        if str(item.get("result", "")).upper() == "PASS" and item.get("real_entry") is True:
            return ["OK G3_5_PASS real-entry smoke evidence is present"]
    return ["FAIL G3_5_BLOCKED no real-entry smoke PASS evidence has been registered"]


def load_test_results(root: Path) -> list[dict[str, object]] | str:
    path = root / TEST_RESULTS_PATH
    if not path.exists():
        return f"FAIL G3_BLOCKED missing {to_posix(TEST_RESULTS_PATH)}"
    try:
      data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
      return f"FAIL G3_BLOCKED invalid {to_posix(TEST_RESULTS_PATH)} JSON: {exc}"
    tests = data.get("tests")
    if not isinstance(tests, list):
        return f"FAIL G3_BLOCKED {to_posix(TEST_RESULTS_PATH)} must contain a tests array"
    return [item for item in tests if isinstance(item, dict)]


def check_changes(root: Path) -> list[str]:
    changes_dir = root / "project/06_changes"
    if not changes_dir.is_dir():
        return ["FAIL MISSING_REQUIRED_DIR project/06_changes"]

    records = sorted(path for path in changes_dir.glob("CR-*.md") if path.is_file())
    findings: list[str] = []
    for record in records:
        text = read_text(record)
        missing = [label for label in CHANGE_REQUIRED_LABELS if f"{label}：" not in text and f"{label}:" not in text]
        if missing:
            rel_path = to_posix(record.relative_to(root))
            findings.append(f"FAIL CHANGE_RECORD_INCOMPLETE {rel_path} missing: {', '.join(missing)}")

    if findings:
        return findings
    if not records:
        return ["OK CHANGE_RECORDS_PASS no change records to validate"]
    return [f"OK CHANGE_RECORDS_PASS validated {len(records)} change record(s)"]


# --- Consensus review gates (CR-20260909-consensus-review-gates) -----------------

# Which spec doc each review level's coverage check reads.
REVIEW_LAYER_DOC = {
    "r2": "project/02_solution/架构设计说明书.md",
    "r3": "project/03_modules/模块任务开发说明书.md",
    "r4": "project/04_tests/测试说明书.md",
}
REVIEW_ROLES = ["产品", "架构", "模块", "测试"]
REVIEW_VERDICTS = ("APPROVED", "CONDITIONAL", "REJECTED")


def _section(text: str, heading_pattern: str) -> str:
    """Body of the first `##`/`###` section whose heading matches, up to the next heading of same-or-higher level."""
    match = re.search(rf"^(#{{2,3}})\s*{heading_pattern}[^\n]*\n", text, re.MULTILINE)
    if not match:
        return ""
    level = len(match.group(1))
    start = match.end()
    tail = text[start:]
    end = re.search(rf"^#{{1,{level}}}\s", tail, re.MULTILINE)
    return tail[: end.start()] if end else tail


def _table_rows(section: str) -> list[list[str]]:
    """Data rows of the first markdown table in a section (skips header + separator)."""
    lines = [line.strip() for line in section.splitlines() if line.strip().startswith("|")]
    rows = [[cell.strip() for cell in line.strip().strip("|").split("|")] for line in lines]
    # Drop the header row and the |---|---| separator row.
    return [row for row in rows[2:] if any(cell for cell in row)]


def _cr_scoped_text(doc_text: str, cr_name: str) -> str:
    """Concatenated bodies of every `##`/`###` section whose heading names this CR.

    CP-coverage must be judged inside the CR's own sections of a layer doc, not
    the whole file — layer docs accumulate `CP-N` mentions from many CRs and a
    bare `\\bCP-3\\b` search would match an unrelated CR's section.
    """
    lines = doc_text.splitlines(keepends=True)
    out: list[str] = []
    i = 0
    while i < len(lines):
        heading = re.match(r"^(#{2,3})\s", lines[i])
        if heading and re.search(re.escape(cr_name), lines[i]):
            level = len(heading.group(1))
            out.append(lines[i])
            i += 1
            while i < len(lines) and not re.match(rf"^#{{1,{level}}}\s", lines[i]):
                out.append(lines[i])
                i += 1
            continue
        i += 1
    return "".join(out)


def parse_cp_registry(cr_text: str) -> list[dict[str, str]]:
    """Rows of a CR's `## 变化点登记` table: [{cp, role}, ...]. Empty when the CR predates the model."""
    section = _section(cr_text, "变化点登记")
    if not section:
        return []
    out: list[dict[str, str]] = []
    for row in _table_rows(section):
        cp = re.search(r"\bCP-\d+\b", row[0]) if row else None
        if cp:
            out.append({"cp": cp.group(0), "role": row[1] if len(row) > 1 else ""})
    return out


def check_review(root: Path, level: str, cr: str | None = None) -> list[str]:
    changes_dir = root / "project/06_changes"
    records = sorted(path for path in changes_dir.glob("CR-*.md") if path.is_file())

    with_model = [(path, parse_cp_registry(read_text(path))) for path in records]
    with_model = [(path, cps) for path, cps in with_model if cps]
    if cr:
        if not (changes_dir / f"{cr}.md").exists():
            return [f"FAIL REVIEW_{level.upper()}_BLOCKED unknown change record: {cr}"]
        with_model = [(path, cps) for path, cps in with_model if path.stem == cr]
    if not with_model:
        return [f"OK REVIEW_{level.upper()}_PASS no change record uses the CP-registry model yet"]

    findings: list[str] = []
    for path, cps in with_model:
        name = path.stem  # e.g. CR-20260909-corner-menu
        cr_text = read_text(path)
        cp_ids = [entry["cp"] for entry in cps]

        if level == "r1":
            for entry in cps:
                if not entry["role"]:
                    findings.append(f"FAIL REVIEW_R1_BLOCKED {name}: {entry['cp']} has no 来源角色")
            if not re.search(r"R1[^\n]*(拍板|终裁|人工确认)", cr_text):
                findings.append(f"FAIL REVIEW_R1_BLOCKED {name}: no R1 human sign-off marker (expected 'R1 … 拍板/终裁')")
            continue

        # r2 / r3 / r4: downward coverage + review matrix.
        layer_text = read_text(root / REVIEW_LAYER_DOC[level])
        scoped = _cr_scoped_text(layer_text, name)
        if not scoped:
            findings.append(
                f"FAIL REVIEW_{level.upper()}_BLOCKED {name}: {REVIEW_LAYER_DOC[level]} has no '## {name} …' section"
            )
        uncovered = [cp for cp in cp_ids if not re.search(rf"\b{re.escape(cp)}\b", scoped)]
        if uncovered:
            findings.append(
                f"FAIL REVIEW_{level.upper()}_COVERAGE_GAP {name}: {', '.join(uncovered)} not addressed in {REVIEW_LAYER_DOC[level]}"
            )

        matrix = _section(cr_text, rf"R{level[1]}\s*评审矩阵")
        if not matrix:
            findings.append(f"FAIL REVIEW_{level.upper()}_MATRIX_INVALID {name}: no '## R{level[1]} 评审矩阵' section")
            continue
        header = next((line for line in matrix.splitlines() if line.strip().startswith("|")), "")
        for role in REVIEW_ROLES:
            if role not in header:
                findings.append(f"FAIL REVIEW_{level.upper()}_MATRIX_INVALID {name}: matrix missing the {role} column")
        rows = _table_rows(matrix)
        matrix_cps = {re.search(r"\bCP-\d+\b", row[0]).group(0) for row in rows if row and re.search(r"\bCP-\d+\b", row[0])}
        for cp in cp_ids:
            if cp not in matrix_cps:
                findings.append(f"FAIL REVIEW_{level.upper()}_MATRIX_INVALID {name}: {cp} has no row in the matrix")
        for row in rows:
            cp_cell = re.search(r"\bCP-\d+\b", row[0]) if row else None
            if not cp_cell:
                continue
            for cell in row[1:5]:
                if not cell:
                    findings.append(f"FAIL REVIEW_{level.upper()}_MATRIX_INVALID {name}: {cp_cell.group(0)} has an empty verdict cell")
                    continue
                if "REJECTED" in cell:
                    findings.append(
                        f"FAIL REVIEW_{level.upper()}_BLOCKED {name}: {cp_cell.group(0)} has a REJECTED verdict — feed back to the layer owner"
                    )
                elif not any(v in cell for v in REVIEW_VERDICTS):
                    findings.append(
                        f"FAIL REVIEW_{level.upper()}_MATRIX_INVALID {name}: {cp_cell.group(0)} cell has no APPROVED/CONDITIONAL/REJECTED verdict"
                    )
                elif "CONDITIONAL" in cell and len(cell.replace("CONDITIONAL", "").strip(" *·:：-")) < 4:
                    findings.append(
                        f"FAIL REVIEW_{level.upper()}_MATRIX_INVALID {name}: {cp_cell.group(0)} has a CONDITIONAL with no condition text"
                    )

    if findings:
        return findings
    return [
        f"OK REVIEW_{level.upper()}_PASS {len(with_model)} change record(s) satisfy the {level.upper()} consensus gate"
    ]


# --- CR-20260910-process-hardening: scoping, stages, scaffolding, spec contract ---

def cr_related_tests(root: Path, cr: str) -> set[str] | None:
    """
    The TEST ids a change record claims, read from its `- 影响测试:` label.
    None when the change record does not exist.
    """
    path = root / "project/06_changes" / f"{cr}.md"
    if not path.exists():
        return None
    for line in read_text(path).splitlines():
        stripped = line.strip()
        if stripped.startswith("- 影响测试"):
            return extract_ids(stripped, "TEST")
    return set()


# Which gates each stage must clear. `release` is deliberately the only one that
# runs g4, and it refuses --cr so a narrowing view can never relax a release.
STAGE_GATES: dict[str, list[str]] = {
    "p1": ["verify", "check-changes", "review r1"],
    "p2": ["verify", "check-changes", "check-specs", "gate g1", "gate g2",
           "review r1", "review r2", "review r3", "review r4"],
    "p3": ["verify", "check-changes", "check-specs", "ui", "gate g1", "gate g2", "gate g3", "gate g3.5",
           "review r1", "review r2", "review r3", "review r4"],
    "release": ["verify", "check-changes", "check-specs", "ui", "gate g1", "gate g2", "gate g3", "gate g3.5",
                "gate g4", "review r1", "review r2", "review r3", "review r4"],
}


def check_stage(root: Path, stage: str, cr: str | None = None) -> list[str]:
    """Run every gate a stage requires (CP-3). One command instead of a dozen."""
    if stage == "release" and cr:
        return ["FAIL STAGE_INVALID release must be judged at full scope; --cr is not accepted"]

    findings: list[str] = []
    for step in STAGE_GATES[stage]:
        head, _, arg = step.partition(" ")
        if head == "verify":
            messages = verify(root)
        elif head == "check-changes":
            messages = check_changes(root)
        elif head == "check-specs":
            messages = check_specs(root)
        elif head == "ui":
            messages = check_ui_process_control(root)
        elif head == "gate":
            messages = gate(root, arg, cr=cr)
        elif head == "review":
            messages = check_review(root, arg, cr=cr)
        else:
            messages = [f"FAIL STAGE_INVALID unknown step: {step}"]
        if not is_ok(messages):
            findings.extend(f"{m}  [{step}]" for m in messages if not m.startswith("OK "))
    if findings:
        return findings
    scope = f" for {cr}" if cr else ""
    return [f"OK STAGE_{stage.upper().replace('.', '_')}_PASS all {len(STAGE_GATES[stage])} gate(s) passed{scope}"]


def new_cr(root: Path, name: str) -> list[str]:
    """Scaffold a compliant change record (CP-4) — all 13 labels, half-width colons."""
    if not name.startswith("CR-"):
        return [f"FAIL NEW_CR_INVALID name must start with 'CR-': {name}"]
    path = root / "project/06_changes" / f"{name}.md"
    if path.exists():
        return [f"FAIL NEW_CR_EXISTS {to_posix(path.relative_to(root))} already exists"]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(cr_template(name), encoding="utf-8", newline="")
    return [f"OK NEW_CR_WRITTEN {to_posix(path.relative_to(root))} - fill the labels, then `matrix {name}`"]


def cr_template(name: str) -> str:
    """All 13 labels CHANGE_REQUIRED_LABELS wants, with half-width colons."""
    lines = [
        f"# {name}",
        "",
        "- 级别: <L1|L2|L3>",
        "- 提出人: <user | 角色>",
        "- 状态: R1 待人工终裁",
        "- 评审模型: R1-R4 + G3/G3.5/G4",
        "- 影响需求: <REQ-... | 无>",
        "- 影响模块: <MOD-... | 无>",
        "- 影响任务: <TASK-... | 无>",
        "- 影响测试: <TEST-... | 无>",
        "- 当前证据: `project/05_evidence/EV-<date>-<slug>.md`",
        "- 方案选项:",
        "  - A. <被否决的选项及其理由>",
        "  - B. **<选中的方案>**",
        "- 选择理由: <为什么选 B - 用证据而非偏好>",
        "- 回滚方式: <文档回滚 + 运行回滚；回滚后重跑 verify | check-changes | review r1..r4 并重新 snapshot>",
        "- 验收条件:",
        "  - R1: 本文件有 `## 变化点登记` 表（每行有来源角色）+ R1 人工终裁痕迹；`review r1` PASS。",
        f"  - R2/R3/R4: 三层说明书各含 `变更响应 · {name}` 节逐一响应全部 CP；本文件三张矩阵无空、无 REJECTED；`review r2|r3|r4` PASS。",
        "  - P3/P4: <任务 DONE、测试 PASS、门禁通过>",
        "- 评审记录: R1 四角色（产品 / 架构 / 模块开发 / 测试）独立评审。**R1 人工终裁**：待用户拍板。",
        "",
        "## 变化点登记",
        "",
        "| CP | 来源角色 | 一句话 | 关联 ID | 类型 |",
        "|---|---|---|---|---|",
        "| CP-1 | 产品 | <一句话> | <REQ-/DEC-/TASK-/TEST-> | <新增/小改/大改/缺陷修复/回归> |",
        "",
        "## R2 / R3 / R4 评审矩阵",
        "",
        f"P2 产出。三层说明书写 `变更响应 · {name}` 节后，跑 `governance.py matrix {name}` 生成矩阵骨架，再逐格填裁决。",
        "",
    ]
    return "\n".join(lines)


def build_matrices(root: Path, cr: str, force: bool = False) -> list[str]:
    """
    Generate R2/R3/R4 matrix skeletons from the CP registry (CP-10).

    Cells are filled with `TODO`, which is not one of the three verdicts - so an
    unfilled matrix fails `review` with MATRIX_INVALID rather than passing quietly.
    """
    path = root / "project/06_changes" / f"{cr}.md"
    if not path.exists():
        return [f"FAIL MATRIX_NO_CR {cr} not found"]
    text = read_text(path)
    cps = parse_cp_registry(text)
    if not cps:
        return [f"FAIL MATRIX_NO_CPS {cr} has no `## 变化点登记` table"]

    notes: list[str] = []
    for level in ("2", "3", "4"):
        heading = f"## R{level} 评审矩阵"
        if heading in text and not force:
            notes.append(f"skipped R{level} (already present; --force to rewrite)")
            continue
        header = "| CP | " + " | ".join(REVIEW_ROLES) + " |"
        rule = "|---" * (len(REVIEW_ROLES) + 1) + "|"
        rows = "\n".join(f"| {entry['cp']} | TODO | TODO | TODO | TODO |" for entry in cps)
        text = text.rstrip() + "\n\n" + heading + "\n\n" + header + "\n" + rule + "\n" + rows + "\n"
        notes.append(f"R{level} ({len(cps)} CP rows)")
    path.write_text(text, encoding="utf-8", newline="")
    return [f"OK MATRIX_WRITTEN {cr}: " + "; ".join(notes)]


# CP-1/CP-12: each spec is "current baseline + per-CR change response + approval".
SPEC_BASELINE_SECTIONS: dict[str, list[str]] = {
    "project/01_specification/产品需求说明书.md": [
        "产品目标", "用户范围", "功能需求", "非功能需求", "非目标", "批准状态",
    ],
    "project/02_solution/架构设计说明书.md": [
        "设计目标", "架构角色定位与文档范围", "技术栈与部署形态", "总体架构", "架构决策",
        "模块边界", "接口契约", "外部 API 证据", "批准状态",
    ],
    "project/03_modules/模块任务开发说明书.md": ["模块任务总览", "关键接口", "批准状态"],
    "project/04_tests/测试说明书.md": ["制定依据", "测试矩阵", "真实入口冒烟", "批准状态"],
}

CHANGE_RESPONSE_PREFIX = "变更响应 · "

# Review content belongs to the change record, never to a spec (CP-2).
REVIEW_HEADING_PATTERNS = [
    re.compile(r"多角色评审"),
    re.compile(r"复盘迭代"),
    re.compile(r"评审（R[1-4]"),
    re.compile(r"R[1-4] 四角色审查"),
    re.compile(r"^CR-\S+\s*评审"),
]


def check_specs(root: Path) -> list[str]:
    """Machine-check the spec structure contract (CP-12, DEC-020 (1))."""
    findings: list[str] = []
    for rel_path, allowed in SPEC_BASELINE_SECTIONS.items():
        path = root / rel_path
        if not path.exists():
            findings.append(f"FAIL SPECS_MISSING {rel_path}")
            continue
        seen: dict[str, int] = {}
        for line in read_text(path).splitlines():
            match = re.match(r"^(#{2,3})\s+(.*?)\s*$", line)
            if not match:
                continue
            level, title = len(match.group(1)), match.group(2)
            if any(pattern.search(title) for pattern in REVIEW_HEADING_PATTERNS):
                findings.append(
                    f"FAIL SPECS_REVIEW_IN_SPEC {rel_path}: review sections belong to the CR - '{title}'"
                )
                continue
            if level != 2:
                continue
            if title.startswith(CHANGE_RESPONSE_PREFIX):
                cr = title[len(CHANGE_RESPONSE_PREFIX):].strip()
                seen[cr] = seen.get(cr, 0) + 1
                continue
            if title not in allowed:
                findings.append(
                    f"FAIL SPECS_UNKNOWN_SECTION {rel_path}: '{title}' is neither a baseline section "
                    f"nor a '{CHANGE_RESPONSE_PREFIX}<CR>' section"
                )
        for cr, count in seen.items():
            if count > 1:
                findings.append(
                    f"FAIL SPECS_DUPLICATE_RESPONSE {rel_path}: {cr} has {count} change-response sections (expected 1)"
                )
    if findings:
        return findings
    return [f"OK SPECS_PASS {len(SPEC_BASELINE_SECTIONS)} spec(s) match the structure contract"]


def check_ui_process_control(root: Path) -> list[str]:
    findings: list[str] = []

    ui_standard_path = root / UI_STANDARD_PATH
    if not ui_standard_path.is_file():
        return [f"FAIL MISSING_REQUIRED_FILE {to_posix(UI_STANDARD_PATH)}"]

    standard_text = read_text(ui_standard_path)
    missing_markers = [marker for marker in UI_REQUIRED_MARKERS if marker not in standard_text]
    if missing_markers:
        findings.append(
            "FAIL UI_STANDARD_INCOMPLETE "
            f"{to_posix(UI_STANDARD_PATH)} missing: {', '.join(missing_markers)}"
        )

    package_path = root / "package.json"
    if not package_path.is_file():
        findings.append("FAIL UI_PACKAGE_MISSING package.json")
    else:
        try:
            package_data = json.loads(package_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            findings.append(f"FAIL UI_PACKAGE_INVALID_JSON package.json {exc}")
        else:
            scripts = package_data.get("scripts")
            if not isinstance(scripts, dict):
                findings.append("FAIL UI_SCRIPTS_MISSING package.json scripts")
            else:
                for script_name in UI_REQUIRED_SCRIPTS:
                    script_value = scripts.get(script_name)
                    if not isinstance(script_value, str) or not script_value.strip():
                        findings.append(f"FAIL UI_SCRIPT_MISSING {script_name}")

    if project_has_ui_source(root):
        if not (root / UI_CONTRACT_SCRIPT_PATH).is_file():
            findings.append(f"FAIL UI_CONTRACT_SCRIPT_MISSING {to_posix(UI_CONTRACT_SCRIPT_PATH)}")
        if not any((root / "tests").glob("**/*.test.tsx")):
            findings.append("FAIL UI_COMPONENT_TEST_MISSING tests/**/*.test.tsx")
        if not any((root / "tests/e2e").glob("*.spec.ts")) and not any((root / "tests/e2e").glob("*.spec.tsx")):
            findings.append("FAIL UI_REAL_ENTRY_TEST_MISSING tests/e2e/*.spec.ts")

    if findings:
        return findings
    return ["OK UI_CONTROL_PASS UI standards, scripts, and interaction coverage controls are present"]


def project_has_ui_source(root: Path) -> bool:
    src_path = root / "src"
    if not src_path.is_dir():
        return False
    return any(src_path.glob("**/*.tsx"))


def append_ledger_event(root: Path, payload: dict[str, object]) -> list[str]:
    ledger_path = root / LEDGER_PATH
    ledger_path.parent.mkdir(parents=True, exist_ok=True)

    existing_findings = check_ledger(root)
    if existing_findings:
        return existing_findings

    events = read_ledger_events(ledger_path)
    previous_hash = events[-1]["hash"] if events else "GENESIS"
    event = {
        "seq": len(events) + 1,
        "timestamp": now_utc(),
        "prev_hash": previous_hash,
        **payload,
    }
    event["hash"] = sha256_text(canonical_json(event))

    with ledger_path.open("a", encoding="utf-8", newline="\n") as handle:
        handle.write(canonical_json(event) + "\n")
    return []


def read_ledger_events(path: Path) -> list[dict[str, object]]:
    if not path.exists():
        return []
    events = []
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.strip():
            events.append(json.loads(line))
    return events


def meaningful_input_exists(text: str) -> bool:
    if "尚未建立" in text or "等待用户确认" in text:
        return False
    normalized = re.sub(r"[\s#`|：:。.,，-]", "", text)
    return len(normalized) >= 20


def contains_placeholder_state(text: str) -> bool:
    return any(marker in text for marker in PLACEHOLDER_MARKERS)


def approved_status_exists(text: str) -> bool:
    return bool(re.search(r"当前状态\s*[：:]\s*APPROVED", text, re.IGNORECASE))


def approved_requirement_row_exists(text: str) -> bool:
    for line in text.splitlines():
        if not line.strip().startswith("|"):
            continue
        if "REQ-" not in line:
            continue
        cells = [cell.strip() for cell in line.strip().strip("|").split("|")]
        if len(cells) < 6:
            continue
        has_priority = cells[2] in {"MUST", "SHOULD", "COULD"}
        has_acceptance = bool(cells[4])
        is_approved = cells[-1].upper() == "APPROVED"
        if has_priority and has_acceptance and is_approved:
            return True
    return False


def extract_ids(text: str, prefix: str) -> set[str]:
    return set(re.findall(rf"\b{re.escape(prefix)}-[A-Z0-9-]+\b", text))


def is_ok(messages: Iterable[str]) -> bool:
    return all(message.startswith("OK ") for message in messages)


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def governed_hash(path: Path, rel_path: str) -> str:
    """
    Baseline hash for a controlled file.

    `tsconfig.json` is special-cased (CR-20260910-process-hardening CP-7): Next.js
    rewrites its `include` array on every build to add whichever `NEXT_DIST_DIR`
    was used, which produced a BASELINE_CHANGED that meant nothing. Only that
    churn is normalised away — every other byte of the file stays controlled.
    """
    if rel_path == "tsconfig.json":
        normalised = normalized_tsconfig(path)
        if normalised is not None:
            return sha256_text(normalised)
    return sha256_file(path)


def normalized_tsconfig(path: Path) -> str | None:
    """Canonical tsconfig text with build-dir type globs dropped from `include`; None when unparseable."""
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    include = data.get("include")
    if isinstance(include, list):
        data["include"] = sorted(
            entry
            for entry in include
            if not (isinstance(entry, str) and re.fullmatch(r"\.next[^/]*/types/\*\*/\*\.ts", entry))
        )
    return canonical_json(data)


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def canonical_json(value: object) -> str:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))


def now_utc() -> str:
    return dt.datetime.now(dt.UTC).replace(microsecond=0).isoformat()


def to_posix(path: Path) -> str:
    return path.as_posix()


def main() -> int:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
    code, output = run()
    sys.stdout.write(output)
    return code


if __name__ == "__main__":
    raise SystemExit(main())
