from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import re
import sys
from pathlib import Path
from typing import Iterable


REQUIRED_FILES = [
    "AGENTS.md",
    "package.json",
    "tools/__init__.py",
    "tools/governance.py",
    "tests/test_governance.py",
    "docs/AI_STANDARD.md",
    "docs/WORKFLOW.md",
    "docs/CONTROLS.md",
    "docs/UI_STANDARD.md",
    "project/00_input/需求输入.md",
    "project/01_specification/产品需求说明书.md",
    "project/02_solution/架构设计说明书.md",
    "project/03_modules/模块任务开发说明书.md",
    "project/04_tests/测试说明书.md",
    "project/05_evidence/README.md",
    "project/06_changes/README.md",
    "project/07_releases/版本发布控制说明书.md",
]

PROJECT_DIRS = [
    "tools",
    "tests",
    "project/00_input",
    "project/01_specification",
    "project/02_solution",
    "project/03_modules",
    "project/04_tests",
    "project/05_evidence",
    "project/06_changes",
    "project/07_releases",
]

CONTROL_DIR = Path("project/.governance")
BASELINE_PATH = CONTROL_DIR / "baseline.json"
LEDGER_PATH = CONTROL_DIR / "ledger.jsonl"
TEST_RESULTS_PATH = Path("project/05_evidence/test-results.json")
UI_STANDARD_PATH = Path("docs/UI_STANDARD.md")

UI_REQUIRED_MARKERS = [
    "UI-GOV-001",
    "Design Tokens",
    "WCAG 2.2 AA",
    "WAI-ARIA Authoring Practices",
    "Component-Driven Development",
    "Testing Library",
    "Playwright",
    "real-entry",
    "third-party provider authorization",
]

UI_REQUIRED_SCRIPTS = [
    "test:auth-ui",
    "test:visual",
    "test:e2e",
    "test:ui-contract",
    "governance:ui",
]

UI_CONTRACT_SCRIPT_PATH = Path("scripts/ui-contract.mjs")

IGNORED_DIR_NAMES = {
    ".git",
    ".data",
    ".next",
    ".turbo",
    ".vercel",
    ".vscode",
    "__pycache__",
    "coverage",
    "node_modules",
    "playwright-report",
    "test-results",
}

# Framework-managed build directories (next.config.mjs NEXT_DIST_DIR isolation).
IGNORED_DIR_PREFIXES = (".next-",)

IGNORED_FILE_NAMES = {
    ".env",
    ".env.local",
    ".env.development",
    ".env.test",
    ".env.production",
    # Regenerated by Next.js on every build/dev; content is not author-controlled.
    "next-env.d.ts",
}

IGNORED_SUFFIXES = {
    ".db",
    ".db-shm",
    ".db-wal",
    ".log",
    ".pyc",
    ".sqlite",
    ".sqlite3",
    ".tsbuildinfo",
}

PLACEHOLDER_MARKERS = [
    "未批准",
    "尚未确认",
    "尚未与用户确认",
    "等待用户确认",
    "产品需求尚未",
    "产品功能需求尚未",
]

CHANGE_REQUIRED_LABELS = [
    "级别",
    "提出人",
    "状态",
    "影响需求",
    "影响模块",
    "影响任务",
    "影响测试",
    "当前证据",
    "方案选项",
    "选择理由",
    "回滚方式",
    "验收条件",
    "评审记录",
]


def run(argv: list[str] | None = None) -> tuple[int, str]:
    parser = build_parser()
    args = parser.parse_args(argv)
    root = Path(args.root).resolve()

    if args.command == "verify":
        messages = verify(root)
    elif args.command == "gate":
        messages = gate(root, args.gate.lower())
    elif args.command == "snapshot":
        messages = snapshot(root, args.actor)
    elif args.command == "check-changes":
        messages = check_changes(root)
    elif args.command == "ui":
        messages = check_ui_process_control(root)
    else:
        parser.error("unknown command")

    code = 0 if all(message.startswith("OK ") for message in messages) else 1
    return code, "\n".join(messages) + "\n"


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Agent-Jarvis governance control CLI")
    subparsers = parser.add_subparsers(dest="command", required=True)

    verify_parser = subparsers.add_parser("verify", help="verify required governance files and baseline integrity")
    verify_parser.add_argument("--root", default=".", help="project root")

    gate_parser = subparsers.add_parser("gate", help="run a governance gate")
    gate_parser.add_argument("gate", choices=["g1", "g2", "g3", "g3.5", "g4"])
    gate_parser.add_argument("--root", default=".", help="project root")

    snapshot_parser = subparsers.add_parser("snapshot", help="write baseline hashes and append a ledger event")
    snapshot_parser.add_argument("--root", default=".", help="project root")
    snapshot_parser.add_argument("--actor", default="unknown", help="actor recorded in the ledger")

    changes_parser = subparsers.add_parser("check-changes", help="validate change records")
    changes_parser.add_argument("--root", default=".", help="project root")

    ui_parser = subparsers.add_parser("ui", help="validate UI process controls")
    ui_parser.add_argument("--root", default=".", help="project root")

    return parser


def verify(root: Path) -> list[str]:
    findings: list[str] = []
    findings.extend(check_required_structure(root))
    findings.extend(m for m in check_ui_process_control(root) if not m.startswith("OK "))
    findings.extend(check_baseline(root))
    findings.extend(check_ledger(root))

    if findings:
        return findings
    return ["OK VERIFY_PASS governance files and integrity checks passed"]


def gate(root: Path, gate_name: str) -> list[str]:
    structure_findings = check_required_structure(root)
    if structure_findings:
        return structure_findings

    if gate_name == "g1":
        return check_g1(root)
    if gate_name == "g2":
        g1 = check_g1(root)
        if not is_ok(g1):
            return ["FAIL G2_BLOCKED G1 must pass before G2"] + g1
        return check_g2(root)
    if gate_name == "g3":
        g2 = gate(root, "g2")
        if not is_ok(g2):
            return ["FAIL G3_BLOCKED G2 must pass before implementation validation"] + g2
        return check_g3(root)
    if gate_name == "g3.5":
        g3 = gate(root, "g3")
        if not is_ok(g3):
            return ["FAIL G3_5_BLOCKED G3 must pass before real-entry smoke validation"] + g3
        return check_g35(root)
    if gate_name == "g4":
        lower = gate(root, "g3.5")
        if not is_ok(lower):
            return ["FAIL G4_BLOCKED G3.5 must pass before release"] + lower
        return check_g4(root)
    return [f"FAIL UNKNOWN_GATE unsupported gate: {gate_name}"]


def snapshot(root: Path, actor: str) -> list[str]:
    findings = check_required_structure(root)
    if findings:
        return findings

    baseline = {
        "schema_version": 1,
        "created_at": now_utc(),
        "files": {rel_path: sha256_file(root / rel_path) for rel_path in discover_controlled_files(root)},
    }
    baseline_json = canonical_json(baseline)
    baseline["baseline_sha256"] = sha256_text(baseline_json)

    baseline_path = root / BASELINE_PATH
    baseline_path.parent.mkdir(parents=True, exist_ok=True)
    baseline_path.write_text(canonical_json(baseline) + "\n", encoding="utf-8")

    ledger_findings = append_ledger_event(
        root,
        {
            "action": "snapshot",
            "actor": actor,
            "payload_sha256": baseline["baseline_sha256"],
            "files": baseline["files"],
        },
    )
    if ledger_findings:
        return ledger_findings

    return [f"OK SNAPSHOT_WRITTEN {to_posix(BASELINE_PATH)}"]


def check_required_structure(root: Path) -> list[str]:
    findings: list[str] = []
    for rel_dir in PROJECT_DIRS:
        if not (root / rel_dir).is_dir():
            findings.append(f"FAIL MISSING_REQUIRED_DIR {rel_dir}")
    for rel_path in REQUIRED_FILES:
        if not (root / rel_path).is_file():
            findings.append(f"FAIL MISSING_REQUIRED_FILE {rel_path}")
    return findings


def check_baseline(root: Path) -> list[str]:
    baseline_path = root / BASELINE_PATH
    if not baseline_path.exists():
        return []

    try:
        baseline = json.loads(baseline_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        return [f"FAIL BASELINE_INVALID_JSON {to_posix(BASELINE_PATH)} {exc}"]

    findings: list[str] = []
    files = baseline.get("files")
    if not isinstance(files, dict):
        return [f"FAIL BASELINE_INVALID_SCHEMA {to_posix(BASELINE_PATH)} missing files object"]

    for rel_path, expected_hash in files.items():
        path = root / rel_path
        if not path.exists():
            findings.append(f"FAIL BASELINE_FILE_MISSING {rel_path}")
            continue
        actual_hash = sha256_file(path)
        if actual_hash != expected_hash:
            findings.append(f"FAIL BASELINE_CHANGED {rel_path}")

    current_files = set(discover_controlled_files(root))
    baseline_files = set(files)
    for rel_path in sorted(current_files - baseline_files):
        findings.append(f"FAIL UNBASELINED_FILE {rel_path}")
    return findings


def discover_controlled_files(root: Path) -> list[str]:
    files: list[str] = []
    for path in root.rglob("*"):
        if not path.is_file():
            continue
        rel_path = path.relative_to(root)
        rel_parts = rel_path.parts
        if any(part in IGNORED_DIR_NAMES for part in rel_parts[:-1]):
            continue
        if any(part.startswith(IGNORED_DIR_PREFIXES) for part in rel_parts[:-1]):
            continue
        if rel_path.parts[:2] == ("project", ".governance"):
            continue
        if path.name in IGNORED_FILE_NAMES:
            continue
        if any(path.name.endswith(suffix) for suffix in IGNORED_SUFFIXES):
            continue
        files.append(to_posix(rel_path))
    return sorted(files)


def check_ledger(root: Path) -> list[str]:
    ledger_path = root / LEDGER_PATH
    if not ledger_path.exists():
        return []

    findings: list[str] = []
    previous_hash = "GENESIS"
    expected_seq = 1
    for line_number, line in enumerate(ledger_path.read_text(encoding="utf-8").splitlines(), start=1):
        if not line.strip():
            continue
        try:
            event = json.loads(line)
        except json.JSONDecodeError as exc:
            findings.append(f"FAIL LEDGER_INVALID_JSON line={line_number} {exc}")
            continue

        if event.get("seq") != expected_seq:
            findings.append(f"FAIL LEDGER_BAD_SEQUENCE line={line_number}")
        if event.get("prev_hash") != previous_hash:
            findings.append(f"FAIL LEDGER_BROKEN_CHAIN line={line_number}")

        recorded_hash = event.get("hash")
        event_without_hash = dict(event)
        event_without_hash.pop("hash", None)
        actual_hash = sha256_text(canonical_json(event_without_hash))
        if recorded_hash != actual_hash:
            findings.append(f"FAIL LEDGER_HASH_MISMATCH line={line_number}")

        previous_hash = str(recorded_hash)
        expected_seq += 1

    return findings


def check_g1(root: Path) -> list[str]:
    input_text = read_text(root / "project/00_input/需求输入.md")
    spec_text = read_text(root / "project/01_specification/产品需求说明书.md")
    findings: list[str] = []

    if not meaningful_input_exists(input_text):
        findings.append("FAIL G1_BLOCKED 原始需求输入缺失或尚未建立")
    if contains_placeholder_state(spec_text):
        findings.append("FAIL G1_BLOCKED 产品需求仍处于未确认状态，需要用户确认")
    if not approved_status_exists(spec_text):
        findings.append("FAIL G1_BLOCKED 产品需求说明书缺少 APPROVED 状态")
    if "用户确认" not in spec_text:
        findings.append("FAIL G1_BLOCKED 产品需求说明书缺少用户确认记录")
    if not approved_requirement_row_exists(spec_text):
        findings.append("FAIL G1_BLOCKED 产品需求说明书缺少带验收标准的已批准需求行")

    if findings:
        return findings
    return ["OK G1_PASS requirements baseline is approved and testable"]


def check_g2(root: Path) -> list[str]:
    architecture = read_text(root / "project/02_solution/架构设计说明书.md")
    modules = read_text(root / "project/03_modules/模块任务开发说明书.md")
    tests = read_text(root / "project/04_tests/测试说明书.md")
    findings: list[str] = []

    for rel_path, text in [
        ("project/02_solution/架构设计说明书.md", architecture),
        ("project/03_modules/模块任务开发说明书.md", modules),
        ("project/04_tests/测试说明书.md", tests),
    ]:
        if contains_placeholder_state(text):
            findings.append(f"FAIL G2_BLOCKED {rel_path} is still unapproved")

    requirement_ids = extract_ids(read_text(root / "project/01_specification/产品需求说明书.md"), "REQ")
    module_requirement_ids = extract_ids(modules, "REQ")
    test_requirement_ids = extract_ids(tests, "REQ")
    task_ids = extract_ids(modules, "TASK")
    test_ids = extract_ids(tests, "TEST")

    missing_module_coverage = sorted(requirement_ids - module_requirement_ids)
    missing_test_coverage = sorted(requirement_ids - test_requirement_ids)
    if missing_module_coverage:
        findings.append(f"FAIL G2_BLOCKED requirements missing module coverage: {', '.join(missing_module_coverage)}")
    if missing_test_coverage:
        findings.append(f"FAIL G2_BLOCKED requirements missing test coverage: {', '.join(missing_test_coverage)}")
    if not task_ids:
        findings.append("FAIL G2_BLOCKED no TASK ids defined")
    if not test_ids:
        findings.append("FAIL G2_BLOCKED no TEST ids defined")

    if findings:
        return findings
    return ["OK G2_PASS architecture, modules, and tests cover approved requirements"]


def check_g4(root: Path) -> list[str]:
    release_text = read_text(root / "project/07_releases/版本发布控制说明书.md")
    findings: list[str] = []
    if contains_placeholder_state(release_text):
        findings.append("FAIL G4_BLOCKED release control is still unapproved")
    if "回滚" not in release_text:
        findings.append("FAIL G4_BLOCKED release control missing rollback instructions")
    if findings:
        return findings
    return ["OK G4_PASS release control is approved"]


def check_g3(root: Path) -> list[str]:
    required_tests = extract_ids(read_text(root / "project/04_tests/测试说明书.md"), "TEST")
    evidence = load_test_results(root)
    if isinstance(evidence, str):
        return [evidence]

    results = {item.get("id"): item for item in evidence}
    missing = sorted(test_id for test_id in required_tests if test_id not in results)

    def is_manual(item: dict[str, object]) -> bool:
        return str(item.get("verification", "")).lower() == "manual"

    def is_deferred(item: dict[str, object]) -> bool:
        # A test bound only to a requirement that has been formally deferred
        # (its "blocks" requirement is DEFERRED in the spec). It is not evidence
        # of a shipped behaviour, so it neither passes nor blocks — it is skipped
        # and reported, and returns with the deferring CR.
        return str(item.get("result", "")).upper() == "DEFERRED"

    pending_manual: list[str] = []
    unattributed_manual: list[str] = []
    deferred: list[str] = []
    failed: list[str] = []

    for test_id in sorted(required_tests):
        item = results.get(test_id)
        if item is None:
            continue
        passed = str(item.get("result", "")).upper() == "PASS"
        if is_deferred(item):
            deferred.append(test_id)
        elif is_manual(item):
            # A manual item cannot be satisfied by a bare "PASS": it must name
            # who verified it and when, so it stays auditable and cannot be
            # silently flipped to green.
            if not passed:
                pending_manual.append(test_id)
            elif not (str(item.get("verified_by", "")).strip() and str(item.get("verified_at", "")).strip()):
                unattributed_manual.append(test_id)
        elif not passed:
            failed.append(test_id)

    findings: list[str] = []
    if missing:
        findings.append(f"FAIL G3_BLOCKED missing PASS evidence for: {', '.join(missing)}")
    if failed:
        findings.append(f"FAIL G3_BLOCKED failing test evidence for: {', '.join(failed)}")
    if pending_manual:
        findings.append(
            "FAIL G3_BLOCKED manual verification pending (a human must run it and record "
            f"verified_by/verified_at): {', '.join(pending_manual)}"
        )
    if unattributed_manual:
        findings.append(
            "FAIL G3_BLOCKED manual verification marked PASS without verified_by/verified_at: "
            f"{', '.join(unattributed_manual)}"
        )
    if findings:
        return findings
    if deferred:
        return [
            "OK G3_PASS all non-deferred required tests have current PASS evidence "
            f"(deferred, tracked by their CR: {', '.join(deferred)})"
        ]
    return ["OK G3_PASS all required tests have current PASS evidence"]


def check_g35(root: Path) -> list[str]:
    evidence = load_test_results(root)
    if isinstance(evidence, str):
        return [evidence.replace("G3_BLOCKED", "G3_5_BLOCKED")]

    for item in evidence:
        if str(item.get("result", "")).upper() == "PASS" and item.get("real_entry") is True:
            return ["OK G3_5_PASS real-entry smoke evidence is present"]
    return ["FAIL G3_5_BLOCKED no real-entry smoke PASS evidence has been registered"]


def load_test_results(root: Path) -> list[dict[str, object]] | str:
    path = root / TEST_RESULTS_PATH
    if not path.exists():
        return f"FAIL G3_BLOCKED missing {to_posix(TEST_RESULTS_PATH)}"
    try:
      data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
      return f"FAIL G3_BLOCKED invalid {to_posix(TEST_RESULTS_PATH)} JSON: {exc}"
    tests = data.get("tests")
    if not isinstance(tests, list):
        return f"FAIL G3_BLOCKED {to_posix(TEST_RESULTS_PATH)} must contain a tests array"
    return [item for item in tests if isinstance(item, dict)]


def check_changes(root: Path) -> list[str]:
    changes_dir = root / "project/06_changes"
    if not changes_dir.is_dir():
        return ["FAIL MISSING_REQUIRED_DIR project/06_changes"]

    records = sorted(path for path in changes_dir.glob("CR-*.md") if path.is_file())
    findings: list[str] = []
    for record in records:
        text = read_text(record)
        missing = [label for label in CHANGE_REQUIRED_LABELS if f"{label}：" not in text and f"{label}:" not in text]
        if missing:
            rel_path = to_posix(record.relative_to(root))
            findings.append(f"FAIL CHANGE_RECORD_INCOMPLETE {rel_path} missing: {', '.join(missing)}")

    if findings:
        return findings
    if not records:
        return ["OK CHANGE_RECORDS_PASS no change records to validate"]
    return [f"OK CHANGE_RECORDS_PASS validated {len(records)} change record(s)"]


def check_ui_process_control(root: Path) -> list[str]:
    findings: list[str] = []

    ui_standard_path = root / UI_STANDARD_PATH
    if not ui_standard_path.is_file():
        return [f"FAIL MISSING_REQUIRED_FILE {to_posix(UI_STANDARD_PATH)}"]

    standard_text = read_text(ui_standard_path)
    missing_markers = [marker for marker in UI_REQUIRED_MARKERS if marker not in standard_text]
    if missing_markers:
        findings.append(
            "FAIL UI_STANDARD_INCOMPLETE "
            f"{to_posix(UI_STANDARD_PATH)} missing: {', '.join(missing_markers)}"
        )

    package_path = root / "package.json"
    if not package_path.is_file():
        findings.append("FAIL UI_PACKAGE_MISSING package.json")
    else:
        try:
            package_data = json.loads(package_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            findings.append(f"FAIL UI_PACKAGE_INVALID_JSON package.json {exc}")
        else:
            scripts = package_data.get("scripts")
            if not isinstance(scripts, dict):
                findings.append("FAIL UI_SCRIPTS_MISSING package.json scripts")
            else:
                for script_name in UI_REQUIRED_SCRIPTS:
                    script_value = scripts.get(script_name)
                    if not isinstance(script_value, str) or not script_value.strip():
                        findings.append(f"FAIL UI_SCRIPT_MISSING {script_name}")

    if project_has_ui_source(root):
        if not (root / UI_CONTRACT_SCRIPT_PATH).is_file():
            findings.append(f"FAIL UI_CONTRACT_SCRIPT_MISSING {to_posix(UI_CONTRACT_SCRIPT_PATH)}")
        if not any((root / "tests").glob("**/*.test.tsx")):
            findings.append("FAIL UI_COMPONENT_TEST_MISSING tests/**/*.test.tsx")
        if not any((root / "tests/e2e").glob("*.spec.ts")) and not any((root / "tests/e2e").glob("*.spec.tsx")):
            findings.append("FAIL UI_REAL_ENTRY_TEST_MISSING tests/e2e/*.spec.ts")

    if findings:
        return findings
    return ["OK UI_CONTROL_PASS UI standards, scripts, and interaction coverage controls are present"]


def project_has_ui_source(root: Path) -> bool:
    src_path = root / "src"
    if not src_path.is_dir():
        return False
    return any(src_path.glob("**/*.tsx"))


def append_ledger_event(root: Path, payload: dict[str, object]) -> list[str]:
    ledger_path = root / LEDGER_PATH
    ledger_path.parent.mkdir(parents=True, exist_ok=True)

    existing_findings = check_ledger(root)
    if existing_findings:
        return existing_findings

    events = read_ledger_events(ledger_path)
    previous_hash = events[-1]["hash"] if events else "GENESIS"
    event = {
        "seq": len(events) + 1,
        "timestamp": now_utc(),
        "prev_hash": previous_hash,
        **payload,
    }
    event["hash"] = sha256_text(canonical_json(event))

    with ledger_path.open("a", encoding="utf-8", newline="\n") as handle:
        handle.write(canonical_json(event) + "\n")
    return []


def read_ledger_events(path: Path) -> list[dict[str, object]]:
    if not path.exists():
        return []
    events = []
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.strip():
            events.append(json.loads(line))
    return events


def meaningful_input_exists(text: str) -> bool:
    if "尚未建立" in text or "等待用户确认" in text:
        return False
    normalized = re.sub(r"[\s#`|：:。.,，-]", "", text)
    return len(normalized) >= 20


def contains_placeholder_state(text: str) -> bool:
    return any(marker in text for marker in PLACEHOLDER_MARKERS)


def approved_status_exists(text: str) -> bool:
    return bool(re.search(r"当前状态\s*[：:]\s*APPROVED", text, re.IGNORECASE))


def approved_requirement_row_exists(text: str) -> bool:
    for line in text.splitlines():
        if not line.strip().startswith("|"):
            continue
        if "REQ-" not in line:
            continue
        cells = [cell.strip() for cell in line.strip().strip("|").split("|")]
        if len(cells) < 6:
            continue
        has_priority = cells[2] in {"MUST", "SHOULD", "COULD"}
        has_acceptance = bool(cells[4])
        is_approved = cells[-1].upper() == "APPROVED"
        if has_priority and has_acceptance and is_approved:
            return True
    return False


def extract_ids(text: str, prefix: str) -> set[str]:
    return set(re.findall(rf"\b{re.escape(prefix)}-[A-Z0-9-]+\b", text))


def is_ok(messages: Iterable[str]) -> bool:
    return all(message.startswith("OK ") for message in messages)


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def canonical_json(value: object) -> str:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))


def now_utc() -> str:
    return dt.datetime.now(dt.UTC).replace(microsecond=0).isoformat()


def to_posix(path: Path) -> str:
    return path.as_posix()


def main() -> int:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
    code, output = run()
    sys.stdout.write(output)
    return code


if __name__ == "__main__":
    raise SystemExit(main())
